services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - .env.prod
    volumes:
      - ./logs:/usr/src/app/logs
      - ./package.json:/usr/src/app/package.json
      - ./src:/usr/src/app/src
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:5000/health', res => console.log(res.statusCode))"]
      interval: 60s
      timeout: 10s
      retries: 3